#? ---- . ---- ---- ---- ---- . ----
#? services:
#? ---- . ---- ---- ---- ---- . ----
services:
  # ---- . ---- ---- ---- ---- . ----
  # analysis:
  # ---- . ---- ---- ---- ---- . ----
  analysis:
    image: wslda-vortex-analysis
    privileged: true
    build:
      context: ./services/wslda-vortex-analysis
      dockerfile: dev-ubuntu-24.10.dockerfile
      additional_contexts:
        app: ${ENV_APP_ANALYSIS_WORKDIR_HOST}
        results_data: ${ENV_APP_ANALYSIS_RESULTS_DATA_DIR_HOST}
        results_analysis: ${ENV_APP_ANALYSIS_RESULTS_ANALYSIS_DIR_HOST}
      args:
        # app analysis's:
        - ARG_APP_ANALYSIS_TIMEZONE=${ENV_APP_ANALYSIS_TIMEZONE}
        - ARG_APP_ANALYSIS_LOCALE=${ENV_APP_ANALYSIS_LOCALE}
        - ARG_APP_ANALYSIS_WORKDIR_HOST=${ENV_APP_ANALYSIS_WORKDIR_HOST}
        - ARG_APP_ANALYSIS_WORKDIR_CNTR=${ENV_APP_ANALYSIS_WORKDIR_CNTR}
        - ARG_APP_ANALYSIS_RESULTS_DATA_DIR_HOST=${ENV_APP_ANALYSIS_RESULTS_DATA_DIR_HOST}
        - ARG_APP_ANALYSIS_RESULTS_DATA_DIR_CNTR=${ENV_APP_ANALYSIS_RESULTS_DATA_DIR_CNTR}
        - ARG_APP_ANALYSIS_RESULTS_ANALYSIS_DIR_HOST=${ENV_APP_ANALYSIS_RESULTS_ANALYSIS_DIR_HOST}
        - ARG_APP_ANALYSIS_RESULTS_ANALYSIS_DIR_CNTR=${ENV_APP_ANALYSIS_RESULTS_ANALYSIS_DIR_CNTR}
    volumes:
      # workdir:
      - ${ENV_APP_ANALYSIS_WORKDIR_HOST}:${ENV_APP_ANALYSIS_WORKDIR_CNTR}
      # results-data-dir:
      - ${ENV_APP_ANALYSIS_RESULTS_DATA_DIR_HOST}:${ENV_APP_ANALYSIS_RESULTS_DATA_DIR_CNTR}
      # results-analysis-dir:
      - ${ENV_APP_ANALYSIS_RESULTS_ANALYSIS_DIR_HOST}:${ENV_APP_ANALYSIS_RESULTS_ANALYSIS_DIR_CNTR}
    networks:
      - net_internal
    stdin_open: true
    tty: true

#? ---- . ---- ---- ---- ---- . ----
#? networks:
#? ---- . ---- ---- ---- ---- . ----
networks:
  net_internal:
    driver: bridge
